// Auto generated by build.sh at Fri Oct  4 19:33:38 UTC 2013

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("9.0.0.1633")]
[assembly: AssemblyFileVersion("9.0.0.1633")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/VersionOne.Client.VisualStudio/wiki")]

[assembly: AssemblyProduct("VersionOne.VisualStudio.VSPackage")]
[assembly: AssemblyTitle("VersionOne.VisualStudio.VSPackage")]
[assembly: AssemblyDescription("VersionOne Client for Visual Studio VersionOne.VisualStudio.VSPackage Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
